export const dataPerson = [
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    reference: 'ERP',
    corporateName: 'Pessoa Cadastrada',
    socialName: 'Nome Cadastrado',
    document: '0000000000',
    phone: '(85) 9 8103.0325',
    email: 'email@mail.com.br',
    address: 'Rua 0001',
    numberAddress: '0221',
    complement: 'Sem Complemento',
    district: 'Aldeota',
    city: 'Fortaleza',
    state: 'CE',
  },
]
